name: xeof
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - dask-core
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.9
  - versioneer
  - xarray>=0.20.0
  - pip:
    - ipykernel
    - pytest
    - pytest-cov
    - pre-commit
    - setuptools
